name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_VITE_SUPABASE_PUBLIC_API_KEY: ${{ vars.VITE_SUPABASE_PUBLIC_API_KEY }}
                  envkey_VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
                  file_name: .env.production

            - name: Build project
              run: npm run build

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v3
              with:
                  name: production-files
                  path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
